title: Przepisy
description: Książka kucharska
theme: jekyll-theme-minimal
logo: /assets/img/logo.png
show_downloads: false
google_analytics: UA-634071-21
dirs:
  - title: Zupy
    name: /zupy/
  - title: Dania główne
    name: /dania_glowne/
  - title: Dodatki
    name: /dodatki/
  - title: Desery
    name: /desery/
  - title: Przetwory
    name: /przetwory/